### ISSUE TITLE
About this plugin.

### ISSUE THREAD

**Issue by whitewabbit** [Liliputech/KohaRecommenderEngine#1]
Can you update this plugin? It seems it doesn't work anymore.

**Comment by black23** [comment]
updated on 17.05 by https://github.com/Liliputech/KohaRecommenderEngine/pull/2

**Comment by whitewabbit** [comment]
Thanks :D btw how to move the recommender to the search result page?

**Comment by Liliputech** [comment]
Hi, I've merged Josef's commit :)
I think you could tinker with OpacJs template to move from the item page to the search result page.
However I wouldn't suggest that since it would compute the recommendations for any search results and probably that would somehow be a performance killer ;)

**Comment by Liliputech** [comment]
Also many thanks to Josef for updating, I don't know when you're from Josef but if you attend Koha's Hackfest, I own you a beer ;)
